language: minimal

services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

git:
  depth: 3

# define several feeds here
env:
  global:
     - PG_USER=postgres
     - PG_DATABASE=postgres

  matrix:
    - FEED=greater-cleveland-regional-transit-authority/214
    - FEED=abq-ride/52
    - FEED=connecticut-transit/323/gtfs.zip
    - FEED=actv/631
    - FEED=transperth/2
    - FEED=greenbus-thailand/784
    - FEED=subterraneos-de-buenos-aires/541

before_install:
  - psql --version
  - make --version

install:
  - make -e init
  - psql -U postgres -c "select postgis_full_version();"

# download latest GTFS data
before_script:
  - curl -Lo gtfs.zip http://transitfeeds.com/p/${FEED}/latest/download
  - make -e drop_constraints

script:
  - make -e load GTFS=gtfs.zip
  - make -e add_constraints

after_script:
  - psql -U postgres -c "SELECT * FROM gtfs_feed_info"
  - psql -U postgres -c "SELECT * FROM gtfs_stop_times LIMIT 10"
  - psql -U postgres -c "SELECT * FROM gtfs_shape_geoms LIMIT 10"
